
replicaCount: 1

image:
  repository: mysql
  tag: "5.5"
  pullPolicy: "ifNotPresent"

service:
  port: 3306
  nodePort: 30006
  targetPort: 3306
  protocol: "TCP"
  type: NodePort

phpmyadmin:
  service:
    - name: phpmyadmin
      protocol: TCP
      port: 8083
      nodePort: 30083
      targetPort: 80
      type: NodePort
  image: 
    - repository: phpmyadmin  
      tag: "5.2.0"
      PMA_HOST: "mysql-service:30006"
      PMA_USER: "root"
      PMA_PASSWORD: "password"
      containerPort: 80

env:
  name: dev