apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-mysql
  namespace: default
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: "{{.Values.image.repository}}:{{.Values.image.tag}}"
        name: {{.Chart.Name}}
        env:
        {{- range .Values.phpmyadmin.image}}        
        - name: MYSQL_ROOT_PASSWORD
          value: "{{.PMA_PASSWORD}}"
        {{ end }}  
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: default   
  labels:
    type: local 
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
     path: "/home/tips/k8mysqlData"      

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: default   
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi