apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-service
  namespace: default
spec:
  type: {{.Values.service.type}}
  selector:
    app: mysql
  ports:
  - protocol: {{.Values.service.protocol | default "TCP"}}
    port: {{.Values.service.port}}      
    nodePort: {{.Values.service.nodePort}}
    targetPort: {{.Values.service.targetPort}}