apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      {{- range .Values.phpmyadmin.image}}
      - image: "{{.repository}}:{{.tag}}"
      {{end}}
        name: {{.Chart.Name}}
        env:
        {{- range .Values.phpmyadmin.image}}
        - name: PMA_HOST
          value: "{{.PMA_HOST}}"
        - name: PMA_USER
          value: "{{.PMA_USER}}"
        - name: PMA_PASSWORD
          value: "{{.PMA_PASSWORD}}"
        {{end}}
        ports:
        {{- range .Values.phpmyadmin.image}}
        - containerPort: {{.containerPort}}
          name: containerport
        {{end}}